#!/bin/bash
#



if [ $# -lt 1 ]
then
  echo "argument does not exist"
  exit 1

else
  pkill hyprpaper  
  rm ~/.config/hypr/preloadedWallpaper/*
  cp $1 ~/.config/hypr/preloadedWallpaper/wallpaper
  hyprpaper &
fi

echo "done!"
