#!/bin/bash

cp -rf ~/.config/hypr ~/../void/projs/dotfiles/.config/
cp -rf ~/scripts/* ~/../void/projs/dotfiles/scripts/
rm ~/../void/projs/dotfiles/scripts/blueConnect

cd ~/../void/projs/dotfiles/
git add -A
git commit -m "scripetd push"
git push

